### ISSUE TITLE
HP doesn't show

### ISSUE THREAD

**Issue by AmazingTeraPlayer** [Lambda11/bam-hp-bar#1]
NA, HP bar still has the question mark.

**Comment by Owyn** [comment]
🤷‍♀  works fine on RU

perhaps you've got errors

**Comment by NotZiora** [comment]
Doesn't work on EU aswell

**Comment by Owyn** [comment]
These messages aren't helpful, you know?

**Comment by NotZiora** [comment]
No error at all
its simply doesnt show any thing 

i called "boss is at 80%" or something and stoppt after this
and no HP bar

**Comment by Lambda11** [comment]
Try with latest version, I added console log messages there for when BAM appears and disappears, when you encounter the problem - copy those messages here, maybe it'd help to see what is wrong

**Comment by IM02** [comment]
> Doesn't work on EU aswell

Working fine for EU

**Comment by yuliegomeow** [comment]
![image](https://user-images.githubusercontent.com/50161290/57005994-dd203a80-6baa-11e9-8bcb-ea8f8e48e478.png)


HP bar is empty but chat notifications still pop up correctly, I think this is the issue for most people.

Edit: There are also no errors 
![image](https://user-images.githubusercontent.com/50161290/57006083-c0d0cd80-6bab-11e9-843a-60d291edcd38.png)

**Comment by IM02** [comment]
I'd say it's one of two 
Pinkie proxy or gpk mod

**Comment by yuliegomeow** [comment]
> I'd say it's one of two
> Pinkie proxy or gpk mod

I don't have any mods and a friend mentioned that his is working while using pinkie's datacenter

**Comment by RobinNorling** [comment]
Same thing happened to me when i was making my version as well, the way i solved it was to emulate another monster instead of the fieldbosses.

```js
let bossInfo = {
	4001: {//Cerrus
		shapeId: 303750,
		template: 1000,
		zone: 994
	},

	501: {//Hazard
		shapeId: 303740,
		template: 77730,
		zone: 777
	},

	5001: {//Ortan
		shapeId: 303730,
		template: 7000,
		zone: 434
	}
};
```

**Comment by Owyn** [comment]
> I don't have any mods

try with a bossbar mod from https://www.essentialmana.com/forums/#/discussion/7268/owyns-ui-mods/p1
and see if it start working

**Comment by Owyn** [comment]
Yea, turns out without modded boss bar it doesn't show...

**Comment by yuliegomeow** [comment]
It works after using the enrage timer boss bar, thanks.

**Comment by RobinNorling** [comment]
```
let bossInfo = {
	4001: {//Cerrus
		shapeId: 303750,
		template: 1000,
		zone: 994
	},

	501: {//Hazard
		shapeId: 303740,
		template: 77730,
		zone: 777
	},

	5001: {//Ortan
		shapeId: 303730,
		template: 7000,
		zone: 434
	}
};

mod.hook('S_SPAWN_NPC', 11, (event) => {
		switch (event.templateId)
		{
			case 5001: // Ortan
			case 4001: // Cerrus
			case 501:  // Hazard
				if(enabled && event.walkSpeed == 240)
				{
					let template = event.templateId;
					gage_info.id = event.gameId;
					gage_info.templateId = bossInfo[template].template;
					gage_info.huntingZoneId = bossInfo[template].zone;
					gage_info.curHp = gage_info.maxHp;
					event.shapeId = bossInfo[template].shapeId;
					console.log("BAM " + event.templateId + " FOUND, and his name is: " + event.npcName + ", id: " + String(event.gameId));
					correct_hp(event.hpLevel);
					load();
					if(event.mode)
					{
						command.message('You missed ~ <font color="#E69F00">' + Math.round((99999999 - event.remainingEnrageTime)/1000) + '</font> sec. of the fight');
					}
					else if(event.hpLevel == 5)
					{
						command.message("BAM is at full 100% hp, nobody touched it");
					}
					else if(event.hpLevel == 0)
					{
						command.message("BAM is likely far below 20% hp, it may die any moment now");
					}
					return true;
				}
		}
});
```
ez

**Comment by Lambda11** [comment]
Thx for that data on similar BAMs @RobinNorling , now I have **fixed** the module to work even if user has no hp bar gpk mod (which is a surprise for me...)
