### ISSUE TITLE
EU new maintenance 

### ISSUE THREAD

**Issue by IM02** [Lambda11/bam-hp-bar#2]
[10:46:40.603] [dispatch] handle: error running hook for S_SPAWN_NPC<11>
hook: (anonymous) in bam-hp-bar
data: { gameId: 8022036836460026n,
  target: 140737490125018n,
  loc: Vec3 { x: 44541.1640625, y: -40801.078125, z: 2033 },
  w: 1.6731895443862632,
  relation: 12,
  templateId: 7000,
  huntingZoneId: 434,
  shapeId: 303730,
  walkSpeed: 240,
  runSpeed: 240,
  status: 2,
  mode: 1,
  remainingEnrageTime: 99839100,
  hpLevel: 1,
  questInfo: 0,
  visible: true,
  villager: false,
  spawnType: 1,
  replaceId: 0n,
  spawnScript: 0,
  replaceDespawnScript: 0,
  aggressive: true,
  owner: 0n,
  occupiedByPartyId: 0n,
  occupiedByPlayerId: 0n,
  bomb: false,
  bySpawnEvent: false,
  bgTeam: 0,
  activeCylinder: 1,
  repairable: true,
  flightInteractionType: 0,
  unkn1: false,
  seats: [],
  parts: [],
  npcName: '거대원숭이(필드보스)' }
error: event is not defined

**Comment by IM02** [comment]
both cerrus and ortan stopped working hazard is good

**Comment by Owyn** [comment]
@IM02 could you post full error ? where error line number is written

**Comment by IM02** [comment]
> @IM02 could you post full error ? where error line number is written

[16:01:05.468] [dispatch] handle: error running hook for S_SPAWN_NPC<11>
hook: (anonymous) in bam-hp-bar
data: { gameId: 8022036837122857n,
  target: 140737490130050n,
  loc: Vec3 { x: -58021.36328125, y: 46949.3125, z: 522 },
  w: -2.2294493275932936,
  relation: 12,
  templateId: 77730,
  huntingZoneId: 777,
  shapeId: 303740,
  walkSpeed: 240,
  runSpeed: 240,
  status: 2,
  mode: 1,
  remainingEnrageTime: 99764905,
  hpLevel: 1,
  questInfo: 0,
  visible: true,
  villager: false,
  spawnType: 1,
  replaceId: 0n,
  spawnScript: 0,
  replaceDespawnScript: 0,
  aggressive: true,
  owner: 0n,
  occupiedByPartyId: 0n,
  occupiedByPlayerId: 0n,
  bomb: false,
  bySpawnEvent: false,
  bgTeam: 0,
  activeCylinder: 1,
  repairable: true,
  flightInteractionType: 0,
  unkn1: false,
  seats: [],
  parts: [],
  npcName: '싸이클롭스(필드보스)' }
error: event is not defined
    at load (E:\Proxy\mods\bam-hp-bar-master\index.js:74:82)
    at Object.mod.hook [as callback] (E:\Proxy\mods\bam-hp-bar-master\index.js:56:5)

**Comment by IM02** [comment]
hazard now

**Comment by Lambda11** [comment]
fixed now, update
