### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhenyateraGG** [Lambda11/bam-hp-bar#4]
[dispatch] [bam-hp-bar] handle: error running hook for S_SPAWN_NPC<11>

**Comment by Owyn** [comment]
so... where's the error? 🤔

**Comment by Tera258** [comment]
[23:50:19.171] [dispatch] [bam-hp-bar] handle: error running hook for S_SPAWN_NPC<11>
hook: (anonymous) in bam-hp-bar
data: {
  gameId: 8022036836866932n,
  target: 140737490867214n,
  loc: Vec3 { x: -44872, y: 45004, z: 135 },
  w: 3.1378535754193217,
  relation: 12,
  templateId: 77730,
  huntingZoneId: 777,
  shapeId: 303740,
  walkSpeed: 240,
  runSpeed: 240,
  status: 2,
  mode: 1,
  remainingEnrageTime: 99996770,
  hpLevel: 4,
  questInfo: 0,
  visible: true,
  villager: false,
  spawnType: 1,
  replaceId: 0n,
  spawnScript: 0,
  replaceDespawnScript: 0,
  aggressive: true,
  owner: 0n,
  occupiedByPartyId: 0n,
  occupiedByPlayerId: 140737490867214n,
  bomb: false,
  bySpawnEvent: false,
  bgTeam: 0,
  activeCylinder: 1,
  repairable: true,
  flightInteractionType: 0,
  unkn1: false,
  seats: [],
  parts: [],
  npcName: '싸이클롭스(필드보스)'
}
error: [dispatch] [bam-hp-bar] hook: Error: obsolete definition (S_EACH_SKILL_RESULT.13)
    at hook (D:\Tera EU\Tera Toolbox\mods\bam-hp-bar\index.js:124:18)
    at load (D:\Tera EU\Tera Toolbox\mods\bam-hp-bar\index.js:94:3)
    at Object.callback (D:\Tera EU\Tera Toolbox\mods\bam-hp-bar\index.js:56:5)

**Comment by zhenyateraGG** [comment]
same

**Comment by Lambda11** [comment]
fixed the error, tell me if it works now (it should)

**Comment by zhenyateraGG** [comment]
Thanks, it works
